backend:
  name: github
  repo: jalferez/backery-ecommerce  # e.g. johnalferez/treetopbakery
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth


media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "bread"
    label: "Bread of the Day"
    folder: "content/bread"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
